# Generated by Django 3.0.4 on 2020-03-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPV', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testresults',
            fields=[
                ('testresults_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('test_squence', models.CharField(blank=True, max_length=255, null=True)),
                ('test_date', models.DateField(blank=True, null=True)),
                ('isc', models.FloatField(blank=True, null=True)),
                ('voc', models.FloatField(blank=True, null=True)),
                ('imp', models.FloatField(blank=True, null=True)),
                ('vmp', models.FloatField(blank=True, null=True)),
                ('pmp', models.FloatField(blank=True, null=True)),
                ('ff', models.FloatField(blank=True, null=True)),
                ('noct', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'testresults',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Testresutls',
        ),
    ]
