# Generated by Django 3.0.5 on 2020-04-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPV', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='report_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
