# Generated by Django 3.0.4 on 2020-03-22 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SolarPV', '0002_auto_20200322_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='contact_person_id',
        ),
    ]
