# Generated by Django 3.0.4 on 2020-03-22 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SolarPV', '0003_auto_20200322_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testlab',
            name='contact_person',
            field=models.ForeignKey(blank=True, db_column='contact_person', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
