# Generated by Django 3.0.4 on 2020-03-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPV', '0005_manufacturer_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='SolarPV.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturing_date',
            field=models.CharField(max_length=8),
        ),
    ]
