# Generated by Django 3.0.4 on 2020-03-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPV', '0006_auto_20200329_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
