# Generated by Django 3.0.4 on 2020-03-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPV', '0007_auto_20200329_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresults',
            old_name='test_squence',
            new_name='test_sequence',
        ),
    ]
