# Generated by Django 3.0.4 on 2020-04-06 16:55

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPV', '0009_auto_20200331_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cell_phone',
            field=phone_field.models.PhoneField(blank=True, default=2554445555, help_text='Cell contact number', max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='office_phone',
            field=phone_field.models.PhoneField(blank=True, default=5553334444, help_text='Office contact number', max_length=31),
            preserve_default=False,
        ),
    ]
