# Generated by Django 3.0.4 on 2020-04-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPV', '0011_certificate_client_location_service_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
