# Generated by Django 3.0.4 on 2020-04-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPV', '0012_auto_20200414_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='postal_code',
            field=models.CharField(default=77777, max_length=5),
        ),
    ]
