# Generated by Django 3.0.4 on 2020-04-16 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPV', '0014_auto_20200416_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SolarPV.Client'),
            preserve_default=False,
        ),
    ]
